server:
  port: 9090
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #启用服务发现机制
      routes:
        - id: user-route
          order: 1
          uri: lb://user-service
          predicates:
            - Path=/common/**
#            - Between=2025-03-21T08:00:00+08:00,2025-03-21T10:00:00+08:00
#            - Header=token,\d+
#            - Query=userid,\d+
#            - Before=2025-03-21T23:59:59+08:00
#            - After=2025-03-21T23:59:59+08:00
#            - Between=2025-03-21T08:00:00+08:00,2025-03-21T23:59:59+08:00
#            - JDK=30
          filters:
            - StripPrefix=1
#            - InvalidParameter=token,-1
        - id: content-route
          order: 1
          uri: lb://content-service
          predicates:
            - Path=/content/**
            - Method=GET
          filters:
            - StripPrefix=1
    sentinel:
      filter:
        enabled: false
      transport:
        port: 8719
        dashboard: localhost:8888
      scg:
        fallback:
          mode: response
          response-status: 500
          response-body: '{"code":500,"msg":"网关流量超量!!"}'