server:
  port: 8082

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8888
      datasource:
        # 流控配置
        flow:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            group-id: sentinel
            rule-type: flow
            data-id: content-service-flow-rules
            data-type: json
        # 熔断降级配置
        degrade:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            group-id: sentinel
            rule-type: degrade
            data-id: content-service-degrade-rules
            data-type: json

feign:
  sentinel:
    enabled: true

